#!/usr/bin/env python3
"""Pack the game's own sepia story panels into src/assets_story.js (data URIs merged into
MV_ASSETS, so the player still works from file://). Kept apart from src/assets.js so that file
need not be regenerated.

    .venv/Scripts/python tools/import_story.py

Source: the "Asriel Story Panels" row of the spriters-resource sheet
asset/PC _ Computer - Undertale - Enemies & Bosses - Asriel Dreemurr.png (five 200 x 110
paintings in the game's five sepia tones, Temmie Chang's art for Asriel's flashback), cut with
tools/slice_sheet.py's cells. Keyed 'story/<name>'.
"""
import base64, io, json, os, sys
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
import slice_sheet

SHEET = slice_sheet.A + 'Enemies & Bosses - Asriel Dreemurr.png'
OUT = 'src/assets_story.js'
# cell index (slice_sheet order) -> name
PANELS = {
    585: 'family',  # the two children with golden flowers in their hands, his and her arms round them
}


def png_uri(img):
    b = io.BytesIO()
    img.save(b, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()


def main():
    cs, _ = slice_sheet.cells(SHEET)
    img, size = {}, {}
    for i, name in PANELS.items():
        c = cs[i]
        assert (c['w'], c['h']) == (200, 110), (i, c['w'], c['h'])
        im = Image.fromarray(c['img'])
        img['story/' + name] = png_uri(im)
        size['story/' + name] = [im.width, im.height]
    with open(OUT, 'w') as f:
        f.write('// Generated by tools/import_story.py (the game\'s sepia story panels) - do not edit.\n')
        f.write('Object.assign(window.MV_ASSETS.img, ')
        json.dump(img, f, separators=(',', ':'))
        f.write(');\nObject.assign(window.MV_ASSETS.size, ')
        json.dump(size, f, separators=(',', ':'))
        f.write(');\n')
    print('panels', len(img), 'bytes', os.path.getsize(OUT))


if __name__ == '__main__':
    main()
